In [62]:
using LinearAlgebraicRepresentation
Lar= LinearAlgebraicRepresentation

LinearAlgebraicRepresentation

In [63]:
using SparseArrays
using DataStructures
using NearestNeighbors

In [64]:
function vertCongruence(W)
	err, i, todelete, vclasses = 10^-5.2,1,[], []
	verts = convert(Lar.Points, W')
	kdtree = NearestNeighbors.KDTree(verts)
	newverts = zeros(Int, size(verts,2))
	for vi in 1:size(verts,2)
		if !(vi in todelete)
			nearvs = NearestNeighbors.inrange(kdtree, verts[:,vi], err)
			push!(vclasses,nearvs)
			newverts[nearvs] .= i
			nearvs = setdiff(nearvs, vi)
			todelete = union(todelete, nearvs)
			i += 1
		end
	end
	V = zeros(3,length(vclasses))
	for (k,class) in enumerate(vclasses)
			V[:,k] = sum(W[class,:],dims=1)/length(class)
	end
	return V, vclasses
end


function cellCongruenceAA(Delta,inclasses)
	cellarray = Lar.cop2lar(Delta)
	new_e = Array{Int64,1}(undef,size(Delta,2))
	for (k,class) in enumerate(inclasses)
		for e in class
			new_e[e] = k
		end
	end
  cells = [map(e->new_e[e], face) for face in cellarray]
  outclasses = DefaultOrderedDict{Array{Int64,1},Array{Int64,1}}([])
  for (k,face) in enumerate(cells)
    if outclasses[face] == []
    	outclasses[face] = [k]
    else
    	append!(outclasses[face],[k])
    end
  end
	FEnew = sort(collect(keys(outclasses)))
  outclasses = sort(collect(values(outclasses)))
  return FEnew,outclasses
end


function chainCongruenceAA(W, T)
	V, vclasses = vertCongruence(W)
	EV, eclasses = cellCongruenceAA(T[1],vclasses)
	FE, fclasses = cellCongruenceAA(T[2],eclasses)
	#@show size(V,2) - size(EV,1) + size(FE,1)
	return V,EV,FE
end

chainCongruenceAA (generic function with 1 method)

In [88]:
V,EV,FE=Lar.randomcubes(30000,.0001)

W = convert(Lar.Points, V');
cop_EV = Lar.coboundary_0(EV::Lar.Cells);
cop_FE = Lar.coboundary_1(FE::Lar.Cells, EV::Lar.Cells);

T = [cop_EV, cop_FE]

2-element Vector{SparseMatrixCSC{Int8, Int64}}:
 sparse([1, 5, 9, 1, 6, 10, 2, 5, 11, 2  …  359997, 359991, 359996, 359998, 359992, 359995, 359999, 359992, 359996, 360000], [1, 1, 1, 2, 2, 2, 3, 3, 3, 4  …  239839, 239840, 239840, 239840, 239841, 239841, 239841, 239842, 239842, 239842], Int8[-1, -1, -1, 1, -1, -1, -1, 1, -1, 1  …  1, 1, -1, 1, -1, 1, 1, 1, 1, 1], 360000, 239842)
 sparse([1, 3, 1, 4, 2, 3, 2, 4, 1, 5  …  179996, 180000, 179997, 179999, 179997, 180000, 179998, 179999, 179998, 180000], [1, 1, 2, 2, 3, 3, 4, 4, 5, 5  …  359996, 359996, 359997, 359997, 359998, 359998, 359999, 359999, 360000, 360000], Int8[1, 1, 1, 1, 1, 1, 1, 1, 1, 1  …  1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 180000, 360000)

# Nove matrici di adiacenza/incidenza

In [27]:
EV = map(Vector{Int64}, EV)

360-element Vector{Vector{Int64}}:
 [1, 2]
 [3, 4]
 [5, 6]
 [7, 8]
 [1, 3]
 [2, 4]
 [5, 7]
 [6, 8]
 [1, 5]
 [2, 6]
 [3, 7]
 [4, 8]
 [9, 10]
 ⋮
 [233, 234]
 [235, 236]
 [237, 238]
 [239, 240]
 [233, 235]
 [234, 236]
 [237, 239]
 [238, 240]
 [233, 237]
 [234, 238]
 [235, 239]
 [236, 240]

In [28]:
FE = map(Vector{Int64}, FE)

180-element Vector{Vector{Int64}}:
 [1, 2, 3, 4]
 [5, 6, 7, 8]
 [1, 2, 5, 6]
 [3, 4, 7, 8]
 [1, 3, 5, 7]
 [2, 4, 6, 8]
 [9, 10, 11, 12]
 [13, 14, 15, 16]
 [9, 10, 13, 14]
 [11, 12, 15, 16]
 [9, 11, 13, 15]
 [10, 12, 14, 16]
 [17, 18, 19, 20]
 ⋮
 [225, 226, 227, 228]
 [229, 230, 231, 232]
 [225, 226, 229, 230]
 [227, 228, 231, 232]
 [225, 227, 229, 231]
 [226, 228, 230, 232]
 [233, 234, 235, 236]
 [237, 238, 239, 240]
 [233, 234, 237, 238]
 [235, 236, 239, 240]
 [233, 235, 237, 239]
 [234, 236, 238, 240]

In [29]:
VV = [[k] for k=1:size(V,2)]

240-element Vector{Vector{Int64}}:
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]
 [10]
 [11]
 [12]
 [13]
 ⋮
 [229]
 [230]
 [231]
 [232]
 [233]
 [234]
 [235]
 [236]
 [237]
 [238]
 [239]
 [240]

In [30]:
VE=EV'

1×360 adjoint(::Vector{Vector{Int64}}) with eltype LinearAlgebra.Adjoint{Int64, Vector{Int64}}:
 [1 2]  [3 4]  [5 6]  [7 8]  [1 3]  [2 4]  …  [234 238]  [235 239]  [236 240]

In [31]:
FE = hcat(FE)

180×1 Matrix{Vector{Int64}}:
 [1, 2, 3, 4]
 [5, 6, 7, 8]
 [1, 2, 5, 6]
 [3, 4, 7, 8]
 [1, 3, 5, 7]
 [2, 4, 6, 8]
 [9, 10, 11, 12]
 [13, 14, 15, 16]
 [9, 10, 13, 14]
 [11, 12, 15, 16]
 [9, 11, 13, 15]
 [10, 12, 14, 16]
 [17, 18, 19, 20]
 ⋮
 [225, 226, 227, 228]
 [229, 230, 231, 232]
 [225, 226, 229, 230]
 [227, 228, 231, 232]
 [225, 227, 229, 231]
 [226, 228, 230, 232]
 [233, 234, 235, 236]
 [237, 238, 239, 240]
 [233, 234, 237, 238]
 [235, 236, 239, 240]
 [233, 235, 237, 239]
 [234, 236, 238, 240]

In [38]:
EV = hcat(EV)

360×1 Matrix{Vector{Int64}}:
 [1, 2]
 [3, 4]
 [5, 6]
 [7, 8]
 [1, 3]
 [2, 4]
 [5, 7]
 [6, 8]
 [1, 5]
 [2, 6]
 [3, 7]
 [4, 8]
 [9, 10]
 ⋮
 [233, 234]
 [235, 236]
 [237, 238]
 [239, 240]
 [233, 235]
 [234, 236]
 [237, 239]
 [238, 240]
 [233, 237]
 [234, 238]
 [235, 239]
 [236, 240]

In [42]:
FV = map(Vector{Int64}, FE * EV)

LoadError: MethodError: mul!(::Matrix{Union{}}, ::Matrix{Vector{Int64}}, ::Matrix{Vector{Int64}}) is ambiguous. Candidates:
  mul!(ret::AbstractMatrix{<:MutableArithmetics.AbstractMutable}, A::AbstractVecOrMat, B::AbstractVecOrMat, args::Vararg{Any, N}) where N in MutableArithmetics at /Users/panemiele/.julia/packages/MutableArithmetics/0Y9ZS/src/dispatch.jl:126
  mul!(ret::AbstractMatrix{<:JuMP.GenericAffOrQuadExpr}, A::AbstractVecOrMat, B::AbstractVecOrMat, args...) in JuMP at /Users/panemiele/.julia/packages/JuMP/iGamg/src/operators.jl:497
Possible fix, define
  mul!(::AbstractMatrix{Union{}}, ::AbstractVecOrMat, ::AbstractVecOrMat, ::Vararg{Any, N}) where N

In [11]:
VF=FV'

1×180 adjoint(::Vector{Vector{Int64}}) with eltype LinearAlgebra.Adjoint{Int64, Vector{Int64}}:
 [1 2 3 4]  [5 6 7 8]  [1 2 5 6]  [3 4 7 8]  [1 3 5 7]  …  [234 236 238 240]

In [14]:
EE = VE * EV

13910520

In [18]:
EF = EV.*VF

360×180 Matrix{Matrix{Int64}}:
 [1 2 3 4; 2 4 6 8]                  …  [234 236 238 240; 468 472 476 480]
 [3 6 9 12; 4 8 12 16]                  [702 708 714 720; 936 944 952 960]
 [5 10 15 20; 6 12 18 24]               [1170 1180 1190 1200; 1404 1416 1428 1440]
 [7 14 21 28; 8 16 24 32]               [1638 1652 1666 1680; 1872 1888 1904 1920]
 [1 2 3 4; 3 6 9 12]                    [234 236 238 240; 702 708 714 720]
 [2 4 6 8; 4 8 12 16]                …  [468 472 476 480; 936 944 952 960]
 [5 10 15 20; 7 14 21 28]               [1170 1180 1190 1200; 1638 1652 1666 1680]
 [6 12 18 24; 8 16 24 32]               [1404 1416 1428 1440; 1872 1888 1904 1920]
 [1 2 3 4; 5 10 15 20]                  [234 236 238 240; 1170 1180 1190 1200]
 [2 4 6 8; 6 12 18 24]                  [468 472 476 480; 1404 1416 1428 1440]
 [3 6 9 12; 7 14 21 28]              …  [702 708 714 720; 1638 1652 1666 1680]
 [4 8 12 16; 8 16 24 32]                [936 944 952 960; 1872 1888 1904 1920]
 [9 18 27 36; 10 20 3

In [25]:
FE = EF'

180×360 adjoint(::Matrix{Matrix{Int64}}) with eltype LinearAlgebra.Adjoint{Int64, Matrix{Int64}}:
 [1 2; 2 4; 3 6; 4 8]                  …  [236 240; 472 480; 708 720; 944 960]
 [5 10; 6 12; 7 14; 8 16]                 [1180 1200; 1416 1440; 1652 1680; 1888 1920]
 [1 2; 2 4; 5 10; 6 12]                   [236 240; 472 480; 1180 1200; 1416 1440]
 [3 6; 4 8; 7 14; 8 16]                   [708 720; 944 960; 1652 1680; 1888 1920]
 [1 2; 3 6; 5 10; 7 14]                   [236 240; 708 720; 1180 1200; 1652 1680]
 [2 4; 4 8; 6 12; 8 16]                …  [472 480; 944 960; 1416 1440; 1888 1920]
 [9 18; 10 20; 11 22; 12 24]              [2124 2160; 2360 2400; 2596 2640; 2832 2880]
 [13 26; 14 28; 15 30; 16 32]             [3068 3120; 3304 3360; 3540 3600; 3776 3840]
 [9 18; 10 20; 13 26; 14 28]              [2124 2160; 2360 2400; 3068 3120; 3304 3360]
 [11 22; 12 24; 15 30; 16 32]             [2596 2640; 2832 2880; 3540 3600; 3776 3840]
 [9 18; 11 22; 13 26; 15 30]           …  [2124 2160; 25

In [17]:
FF= VF .* FV

180×180 Matrix{Int64}:
   30    70    44    64    50    60    110  …    2364    2384    2370    2380
   70   174   100   152   114   140    278       6132    6184    6146    6172
   44   100    66    94    74    88    156       3314    3342    3322    3336
   64   152    94   138   106   128    240       5198    5242    5210    5232
   50   114    74   106    84   100    178       3786    3818    3796    3812
   60   140    88   128   100   120    220  …    4728    4768    4740    4760
  110   278   156   240   178   220    446       9900    9984    9922    9964
  150   382   212   328   242   300    614      13668   13784   13698   13756
  124   308   178   270   202   248    492      10850   10942   10874   10920
  144   360   206   314   234   288    576      12734   12842   12762   12816
  130   322   186   282   212   260    514  …   11322   11418   11348   11396
  140   348   200   304   228   280    556      12264   12368   12292   12344
  190   486   268   416   306   380    78

# <br><br><br><br><br> Chain Congruence

In [26]:
V,VE,FV=chainCongruenceAA(W,T)

([1.1624662 1.1624753 … 1.102137575 1.10213355; 0.5304282499999999 0.5304296500000001 … 0.144851975 0.144851975; 1.000068 1.0000715 … 1.13912805 1.13913365], [[1, 1], [1, 2], [2, 2], [3, 3], [3, 4], [4, 4], [5, 5], [5, 6], [5, 7], [6, 6]  …  [89, 90], [89, 91], [90, 90], [90, 92], [91, 91], [91, 92], [92, 92], [93, 93], [93, 94], [94, 94]], [[1, 1, 1, 1], [1, 2, 3, 3], [2, 2, 2, 2], [4, 4, 4, 4], [4, 5, 6, 6], [5, 5, 5, 5], [7, 7, 9, 10], [7, 8, 13, 14], [8, 8, 11, 12], [9, 11, 13, 13]  …  [131, 133, 135, 137], [132, 134, 136, 138], [139, 139, 141, 142], [139, 140, 145, 146], [140, 140, 143, 144], [141, 143, 145, 145], [142, 144, 146, 146], [147, 147, 148, 149], [148, 148, 148, 148], [149, 149, 149, 149]])

In [27]:
VE

149-element Vector{Vector{Int64}}:
 [1, 1]
 [1, 2]
 [2, 2]
 [3, 3]
 [3, 4]
 [4, 4]
 [5, 5]
 [5, 6]
 [5, 7]
 [6, 6]
 [6, 8]
 [7, 7]
 [7, 8]
 ⋮
 [87, 88]
 [89, 89]
 [89, 90]
 [89, 91]
 [90, 90]
 [90, 92]
 [91, 91]
 [91, 92]
 [92, 92]
 [93, 93]
 [93, 94]
 [94, 94]

In [28]:
FV

120-element Vector{Vector{Int64}}:
 [1, 1, 1, 1]
 [1, 2, 3, 3]
 [2, 2, 2, 2]
 [4, 4, 4, 4]
 [4, 5, 6, 6]
 [5, 5, 5, 5]
 [7, 7, 9, 10]
 [7, 8, 13, 14]
 [8, 8, 11, 12]
 [9, 11, 13, 13]
 [10, 12, 14, 14]
 [15, 15, 16, 17]
 [16, 16, 16, 16]
 ⋮
 [128, 130, 137, 138]
 [129, 130, 133, 134]
 [131, 133, 135, 137]
 [132, 134, 136, 138]
 [139, 139, 141, 142]
 [139, 140, 145, 146]
 [140, 140, 143, 144]
 [141, 143, 145, 145]
 [142, 144, 146, 146]
 [147, 147, 148, 149]
 [148, 148, 148, 148]
 [149, 149, 149, 149]